### ISSUE TITLE
tokio io support

### ISSUE THREAD

**Issue by anatawa12** [thepacketgeek/clap-stdin#4]
`tokio::io::stdin()` or `tokio::fs::File`

**Comment by thepacketgeek** [comment]
Can you please provide more info about how you would use 'tokio' support?

I don't believe this would work for 'MaybeStdIn' since clap doesn't have a mechanism to use 'tokio'. 

Potentially I could add a feature for 'tokio' support for 'FileOrStdin', but I don't see this being advantageous. Clap uses blocking calls, and you only read the contents of the file once prior to starting a 'tokio' runtime.

**Comment by thepacketgeek** [comment]
Thank you for the suggestion! Merged in #5 and will be released as v0.4.0
